"""Typed objects for deterministic knowledge recommendations."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any, Mapping


class RecommendationSeverity(str, Enum):
    """Severity for a knowledge-engine recommendation."""

    INFO = "info"
    WARNING = "warning"
    ERROR = "error"


class RecommendationCategory(str, Enum):
    """Scientific or workflow category for a recommendation."""

    DATASET_SUITABILITY = "dataset_suitability"
    PRODUCT = "product"
    PARAMETER = "parameter"
    CLASSIFICATION = "classification"
    HEIGHT = "height"
    CRS = "crs"
    QGIS_TOOL = "qgis_tool"
    NEXT_ACTION = "next_action"
    SCIENTIFIC_NOTE = "scientific_note"


@dataclass(frozen=True)
class KnowledgeThreshold:
    """Configurable threshold with transparent rationale."""

    name: str
    value: float | None
    unit: str
    rationale: str
    calibration_required: bool = True


@dataclass(frozen=True)
class KnowledgeConfig:
    """Configuration for deterministic knowledge rules.

    Defaults are conservative seed values for planning only. They must remain
    configurable because appropriate lidar density and area thresholds vary by
    forest type, acquisition design, and scientific question.
    """

    high_density_points_per_square_unit: KnowledgeThreshold = KnowledgeThreshold(
        name="high_density_points_per_square_unit",
        value=20.0,
        unit="points per square map unit",
        rationale="Seed planning threshold from Phase 16A examples for considering finer CHM grids; requires calibration.",
    )
    low_density_points_per_square_unit: KnowledgeThreshold = KnowledgeThreshold(
        name="low_density_points_per_square_unit",
        value=5.0,
        unit="points per square map unit",
        rationale="Seed planning threshold from Phase 16A examples for avoiding overly fine rasterization; requires calibration.",
    )
    fine_chm_resolution: KnowledgeThreshold = KnowledgeThreshold(
        name="fine_chm_resolution",
        value=0.5,
        unit="map units",
        rationale="Candidate CHM grid size paired with the configurable high-density seed threshold; not a universal rule.",
    )
    conservative_chm_resolution: KnowledgeThreshold = KnowledgeThreshold(
        name="conservative_chm_resolution",
        value=1.0,
        unit="map units or larger",
        rationale="Candidate CHM grid size for lower-density datasets; final choice should be calibrated to acquisition and canopy structure.",
    )
    minimum_rumple_area: KnowledgeThreshold = KnowledgeThreshold(
        name="minimum_rumple_area",
        value=None,
        unit="square map units",
        rationale="No default area threshold is asserted; configure after literature review or project calibration.",
    )

    def thresholds(self) -> tuple[KnowledgeThreshold, ...]:
        """Return all configured thresholds for report transparency."""
        return (
            self.high_density_points_per_square_unit,
            self.low_density_points_per_square_unit,
            self.fine_chm_resolution,
            self.conservative_chm_resolution,
            self.minimum_rumple_area,
        )


@dataclass(frozen=True)
class Recommendation:
    """Structured recommendation generated by a deterministic rule."""

    code: str
    severity: RecommendationSeverity
    category: RecommendationCategory
    reason: str
    suggested_action: str
    documentation_link: str
    confidence: int
    product: str | None = None
    parameter_name: str | None = None
    parameter_value: object | None = None
    unit: str | None = None
    scientific_note: str | None = None
    calibration_required: bool = False


@dataclass(frozen=True)
class RecommendedProduct:
    """Product-level recommendation derived from Dataset Explorer feasibility."""

    product: str
    label: str
    status: str
    reason: str
    confidence: int


@dataclass(frozen=True)
class RecommendedParameter:
    """Parameter suggestion with rationale and uncertainty flags."""

    product: str
    name: str
    value: object
    unit: str
    reason: str
    confidence: int
    threshold_names: tuple[str, ...] = ()
    calibration_required: bool = True


@dataclass(frozen=True)
class QgisToolSuggestion:
    """Suggestion for an existing QGIS capability."""

    tool_name: str
    reason: str
    when_to_use: str


@dataclass(frozen=True)
class DatasetFacts:
    """Normalized facts extracted from a Dataset Explorer report."""

    source_path: str | None
    point_count: int | None
    estimated_density: float | None
    area: float | None
    crs: str | None
    dimensions: tuple[str, ...]
    classification_counts: Mapping[int, int]
    warnings: tuple[Mapping[str, Any], ...]
    supported_products: tuple[Mapping[str, Any], ...]
    dataset_size_bytes: int | None = None

    @property
    def has_hag(self) -> bool:
        """Return whether HeightAboveGround appears in the dimensions."""
        lowered = {item.lower().replace("_", "") for item in self.dimensions}
        return "heightaboveground" in lowered or "hag" in lowered

    @property
    def has_z(self) -> bool:
        """Return whether Z appears in the dimensions."""
        return "z" in {item.lower() for item in self.dimensions}

    @property
    def has_ground(self) -> bool:
        """Return whether ASPRS ground class 2 has a positive count."""
        return self.classification_counts.get(2, 0) > 0

    @property
    def has_vegetation(self) -> bool:
        """Return whether ASPRS vegetation classes 3, 4, or 5 appear."""
        return any(self.classification_counts.get(code, 0) > 0 for code in (3, 4, 5))

    @property
    def has_classification_summary(self) -> bool:
        """Return whether classification counts are available."""
        return bool(self.classification_counts)
