"""Dependency registry for the managed backend."""

from __future__ import annotations

from .models import BackendDependency, BackendRegistry


_REQUIRED = True
_OPTIONAL = False


def default_backend_registry() -> BackendRegistry:
    """Return the initial registry-driven dependency set for PBM."""
    dependencies = (
        BackendDependency(
            name="micromamba",
            display_name="Micromamba",
            category="environment manager",
            required=_REQUIRED,
            version_spec="stable",
            source="conda-forge bootstrap artifact",
            executable_name="micromamba",
            verification_command=("--version",),
            notes="Phase 22C can download a user-local micromamba binary only when the developer installer guard is enabled.",
        ),
        BackendDependency(
            name="python",
            display_name="Python",
            category="runtime",
            required=_REQUIRED,
            version_spec=">=3.12,<3.13",
            source="conda-forge",
            executable_name="python",
            verification_command=("--version",),
            notes="Managed backend Python, separate from QGIS Python.",
        ),
        BackendDependency(
            name="pdal",
            display_name="PDAL",
            category="geospatial runtime",
            required=_REQUIRED,
            version_spec=">=2.6,<2.9",
            source="conda-forge",
            executable_name="pdal",
            verification_command=("--version",),
        ),
        BackendDependency(
            name="python-pdal",
            display_name="PDAL Python bindings",
            category="python package",
            required=_REQUIRED,
            version_spec="compatible with PDAL runtime",
            source="conda-forge",
            python_import_name="pdal",
        ),
        BackendDependency(
            name="gdal",
            display_name="GDAL Python bindings",
            category="python package",
            required=_REQUIRED,
            version_spec="compatible with rasterio and PDAL stack",
            source="conda-forge",
            executable_name="gdalinfo",
            python_import_name="osgeo.gdal",
            verification_command=("--version",),
        ),
        BackendDependency(
            name="rasterio",
            display_name="rasterio",
            category="python package",
            required=_REQUIRED,
            version_spec="compatible with GDAL backend stack",
            source="conda-forge",
            python_import_name="rasterio",
        ),
        BackendDependency(
            name="numpy",
            display_name="NumPy",
            category="python package",
            required=_REQUIRED,
            version_spec=">=1.26,<2.0",
            source="conda-forge",
            python_import_name="numpy",
        ),
        BackendDependency(
            name="scipy",
            display_name="SciPy",
            category="python package",
            required=_REQUIRED,
            version_spec=">=1.11,<1.15",
            source="conda-forge",
            python_import_name="scipy",
        ),
        BackendDependency(
            name="pandas",
            display_name="pandas",
            category="python package",
            required=_REQUIRED,
            version_spec=">=2.1,<3",
            source="conda-forge",
            python_import_name="pandas",
        ),
        BackendDependency(
            name="shapely",
            display_name="Shapely",
            category="python package",
            required=_REQUIRED,
            version_spec=">=2,<3",
            source="conda-forge",
            python_import_name="shapely",
        ),
        BackendDependency(
            name="pyproj",
            display_name="PyProj",
            category="python package",
            required=_REQUIRED,
            version_spec=">=3.6,<4",
            source="conda-forge",
            python_import_name="pyproj",
        ),
        BackendDependency(
            name="fiona",
            display_name="Fiona",
            category="python package",
            required=_REQUIRED,
            version_spec=">=1.9,<2",
            source="conda-forge",
            python_import_name="fiona",
        ),
        BackendDependency(
            name="geopandas",
            display_name="GeoPandas",
            category="python package",
            required=_REQUIRED,
            version_spec=">=0.14,<1.1",
            source="conda-forge",
            python_import_name="geopandas",
        ),
        BackendDependency(
            name="matplotlib",
            display_name="Matplotlib",
            category="python package",
            required=_REQUIRED,
            version_spec=">=3.8,<3.10",
            source="conda-forge",
            python_import_name="matplotlib",
        ),
        BackendDependency(
            name="tqdm",
            display_name="tqdm",
            category="python package",
            required=_REQUIRED,
            version_spec=">=4.66,<5",
            source="conda-forge",
            python_import_name="tqdm",
        ),
        BackendDependency(
            name="pyforestscan",
            display_name="PyForestScan",
            category="scientific engine",
            required=_REQUIRED,
            version_spec=">=0.4",
            source="PyPI",
            python_import_name="pyforestscan",
        ),
        BackendDependency(
            name="whiteboxtools",
            display_name="WhiteboxTools",
            category="future module",
            required=_OPTIONAL,
            version_spec="future",
            source="future module registry",
            executable_name="whitebox_tools",
            notes="Future terrain/hydrology module candidate.",
        ),
        BackendDependency(
            name="open3d",
            display_name="Open3D",
            category="future module",
            required=_OPTIONAL,
            version_spec="future",
            source="future module registry",
            python_import_name="open3d",
            notes="Future point-cloud visualization or ML module candidate.",
        ),
        BackendDependency(
            name="pytorch",
            display_name="PyTorch",
            category="future module",
            required=_OPTIONAL,
            version_spec="future",
            source="future module registry",
            python_import_name="torch",
            notes="Future deep-learning module candidate.",
        ),
        BackendDependency(
            name="onnx-runtime",
            display_name="ONNX Runtime",
            category="future module",
            required=_OPTIONAL,
            version_spec="future",
            source="future module registry",
            python_import_name="onnxruntime",
            notes="Future model-inference module candidate.",
        ),
        BackendDependency(
            name="segment-anything",
            display_name="Segment Anything",
            category="future module",
            required=_OPTIONAL,
            version_spec="future",
            source="future module registry",
            python_import_name="segment_anything",
            notes="Future imagery segmentation module candidate.",
        ),
        BackendDependency(
            name="cloudcompare-cli",
            display_name="CloudCompare CLI",
            category="future module",
            required=_OPTIONAL,
            version_spec="future",
            source="future module registry",
            executable_name="CloudCompare",
            notes="Future point-cloud utility module candidate.",
        ),
        BackendDependency(
            name="entwine",
            display_name="Entwine",
            category="future module",
            required=_OPTIONAL,
            version_spec="future",
            source="future module registry",
            executable_name="entwine",
            notes="Future EPT generation module candidate.",
        ),
        BackendDependency(
            name="potree-converter",
            display_name="Potree Converter",
            category="future module",
            required=_OPTIONAL,
            version_spec="future",
            source="future module registry",
            executable_name="PotreeConverter",
            notes="Future web point-cloud visualization module candidate.",
        ),
    )
    return BackendRegistry(dependencies=dependencies)
