"""Renderer-neutral workspace interface; implementations expose plain state."""
from enum import Enum
from typing import Protocol


class ViewerState(str, Enum):
    READY = "VIEWER_READY"
    SETUP_REQUIRED = "VIEWER_SETUP_REQUIRED"
    CACHE_BUILDING = "VIEWER_CACHE_BUILDING"
    SOURCE_OPEN = "VIEWER_SOURCE_OPEN"
    SOURCE_ERROR = "VIEWER_SOURCE_ERROR"
    DISCONNECTED = "VIEWER_DISCONNECTED"


class PointCloudViewerBackend(Protocol):
    def open_source(self, source: str) -> None: ...
    def close_source(self) -> None: ...
    def source_info(self) -> dict: ...
    def fit_view(self) -> None: ...
    def set_camera(self, camera: dict) -> None: ...
    def set_point_budget(self, points: int) -> None: ...
    def set_render_mode(self, mode: str) -> None: ...
    def set_class_visibility(self, classes: list[int]) -> None: ...
    def set_height_filter(self, dimension: str, minimum: float, maximum: float) -> None: ...
    def clear_filters(self) -> None: ...
    def pick_point(self, x: float, y: float) -> None: ...
    def begin_selection(self) -> None: ...
    def update_selection(self, geometry: dict) -> None: ...
    def finish_selection(self) -> None: ...
    def clear_selection(self) -> None: ...
    def selection_stats(self) -> dict: ...
    def save_view_state(self) -> dict: ...
    def restore_view_state(self, state: dict) -> None: ...
