"""Core interfaces for PyForestScan QGIS."""

from __future__ import annotations

from .adapter import AdapterProgress, PyForestScanAdapter
from .config import AdapterConfig, DatasetOpenOptions, InspectionOptions
from .dataset_report import (
    DatasetExplorerReport,
    DatasetWarning,
    ProductFeasibility,
    build_dataset_explorer_report,
    format_count_for_display,
    format_crs_for_display,
    format_density_for_display,
    render_html_report,
    render_json_report,
    report_to_dict,
    write_csv_summary,
    write_html_report,
    write_json_report,
)
from .dependency_check import (
    CheckStatus,
    EnvironmentCheckResult,
    EnvironmentReport,
    ReadinessStatus,
    collect_environment_report,
    format_environment_report,
)
from .exceptions import AdapterError, DatasetError, EnvironmentError, ProcessingError
from .job_manager import JobEventSink, JobExecutionError, JobManager
from .job_results import job_to_dict, render_job_summary_json, write_job_summary_json
from .jobs import JobLogRecord, JobMode, JobProgress, JobRecord, JobRequest, JobResultRecord, JobStatus
from .output_loader import OutputLoadRequest
from .project import PyForestScanProject
from .product_plan import (
    PlannedOutput,
    PlannerWarning,
    ProductPlanError,
    ProductPlanItem,
    ProductPlannerReport,
    ProductPlannerRequest,
    build_product_plan,
    load_dataset_explorer_json,
    plan_to_dict,
    render_plan_html,
    render_plan_json,
    write_plan_csv,
    write_plan_html,
    write_plan_json,
)
from .runner import AlgorithmRunRequest
from .workspace import RunContext, create_run_context
from .types import (
    AdapterParameter,
    Bounds3D,
    ClassificationCount,
    DatasetFormat,
    DatasetInspection,
    DatasetSource,
    DatasetValidationResult,
    LogContextItem,
    LogLevel,
    LogRecord,
    ProductRequest,
    ProductResult,
    ProductType,
    ProgressSnapshot,
    ProgressState,
)

__all__ = [
    "AdapterConfig",
    "AdapterError",
    "AdapterParameter",
    "AdapterProgress",
    "AlgorithmRunRequest",
    "Bounds3D",
    "CheckStatus",
    "ClassificationCount",
    "DatasetExplorerReport",
    "DatasetWarning",
    "ProductFeasibility",
    "build_dataset_explorer_report",
    "render_html_report",
    "render_json_report",
    "report_to_dict",
    "write_csv_summary",
    "write_html_report",
    "write_json_report",
    "DatasetError",
    "DatasetFormat",
    "DatasetInspection",
    "DatasetOpenOptions",
    "DatasetSource",
    "DatasetValidationResult",
    "EnvironmentCheckResult",
    "EnvironmentError",
    "EnvironmentReport",
    "InspectionOptions",
    "JobEventSink",
    "JobExecutionError",
    "JobLogRecord",
    "JobManager",
    "JobMode",
    "JobProgress",
    "JobRecord",
    "JobRequest",
    "JobResultRecord",
    "JobStatus",
    "job_to_dict",
    "render_job_summary_json",
    "write_job_summary_json",
    "LogContextItem",
    "LogLevel",
    "LogRecord",
    "OutputLoadRequest",
    "ProcessingError",
    "PlannedOutput",
    "PlannerWarning",
    "ProductPlanError",
    "ProductPlanItem",
    "ProductPlannerReport",
    "ProductPlannerRequest",
    "build_product_plan",
    "load_dataset_explorer_json",
    "plan_to_dict",
    "render_plan_html",
    "render_plan_json",
    "write_plan_csv",
    "write_plan_html",
    "write_plan_json",
    "ProductRequest",
    "ProductResult",
    "ProductType",
    "ProgressSnapshot",
    "ProgressState",
    "PyForestScanAdapter",
    "PyForestScanProject",
    "ReadinessStatus",
    "RunContext",
    "create_run_context",
    "collect_environment_report",
    "format_count_for_display",
    "format_crs_for_display",
    "format_density_for_display",
    "format_environment_report",
]
