const assert = require('node:assert/strict');
const path = require('node:path');
const p = require(path.resolve(__dirname, '../../pyforestscan_qgis/viewer/render_policy.js'));
const v = [271368, 2152762, 100, 0, -.5, 500];
let jitter = [...v]; jitter[0] += .00001;
assert.equal(p.motion(v, jitter, 16, 0, 0, 100).lastMotion, 0);
let motion = [...v]; motion[3] += .1;
const moving = p.motion(v, motion, 16, 0, 0, 100);
assert(moving.velocity > 0);
assert(p.moving(moving.velocity, 100, 200));
assert(!p.moving(moving.velocity, 100, 300));
assert.equal(p.threshold(12, 12.1), 12);
assert(p.threshold(12, 18) < 14);
assert(p.retain('r', ['r03'], 0, 5000, 5000000, 1000000));
assert(p.retain('r1', ['r03'], 4900, 5000, 1100000, 1000000));
assert(!p.retain('r1', ['r03'], 4900, 5000, 2000000, 1000000));
assert(!p.retain('r1', ['r03'], 0, 5000, 1100000, 1000000));
assert.equal(p.size().minimum, 2);
assert(p.size().maximum <= 5);
assert.deepEqual(p.size(8), {minimum:8,maximum:8,scale:8});
assert.equal(p.appearance("Circular", 0).style, "Circular");
assert.equal(p.appearance("Square", 16).size, 16);
for (const invalid of [-1,17,NaN,Infinity,1.5,"8",true]) assert.throws(()=>p.size(invalid));
assert.throws(()=>p.appearance("Voxel", 2));
assert.deepEqual(p.objectFocus("SHOW_ALL", true), {requested:"SHOW_ALL",effective:"SHOW_ALL",opacity:1});
assert.deepEqual(p.objectFocus("FADE_OTHERS", true), {requested:"FADE_OTHERS",effective:"FADE_OTHERS",opacity:.12});
assert.deepEqual(p.objectFocus("ISOLATE", true), {requested:"ISOLATE",effective:"ISOLATE",opacity:0});
assert.equal(p.objectFocus("ISOLATE", false).effective, "SHOW_ALL");
assert.equal(p.objectFocus("ISOLATE", false).opacity, 1);
assert.throws(()=>p.objectFocus("HIDE_SOURCE", true));
console.log('Renderer policy: jitter, velocity, debounce, LOD deadband, parent retention, pressure and point-size checks passed.');
